[package]
name = "openspore-core"
version = "1.2.1"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
config = "0.15.19"
dotenvy = "0.15.7"
tracing = "0.1.44"
thiserror = "2.0.18"
